name: Build

on:
  push:
    branches:
      - '**'
    paths:
      - '*.sln'
      - samples/**
      - src/**
      - .github/workflows/build.yml
    tags-ignore: ['v*']

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2.4.2
      with:
        fetch-depth: 0
        lfs: true
    - uses: microsoft/setup-msbuild@v1.0.2
    - uses: actions/setup-dotnet@v1.0.0
    - name: Build and Test
      run: .\build.ps1 -Version ("$(git describe --abbrev=0 --tags)" -replace 'v([\d.]+)(-.+)?', '$1-dev')
    - name: Upload binaries
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: src/MvvmMicro/bin/Release
