name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0
        lfs: true
    - uses: microsoft/setup-msbuild@v2
    - uses: actions/setup-dotnet@v3.4.2
    - name: Build
      run: .\build.ps1 -Version $Env:GITHUB_REF.Replace('refs/tags/v', '') -Pack
    - name: Upload binaries
      uses: actions/upload-artifact@v4.6.2
      with:
        name: binaries
        path: src/MvvmMicro/bin/Release
    - name: Upload package
      uses: actions/upload-artifact@v4.6.2
      with:
        name: package
        path: package
    - uses: NuGet/setup-nuget@v2.0.0
    - name: Publish package
      run: nuget push package\*.nupkg -source https://www.nuget.org -apikey $Env:NUGET_API_KEY
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        prerelease: ${{ contains(github.ref_name, '-') }}
        files: package\*.nupkg
